name: build-samples

on:
    push:
        branches: [ master, develop*, release* ]
    pull_request:
        branches: [ master, develop*, release* ]
    workflow_dispatch:

jobs:
    build-samples:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                java: [ '8', '11' ]

        steps:
            -   uses: actions/checkout@v3
            -   name: Set up JDK ${{ matrix.Java }}
                uses: actions/setup-java@v3
                with:
                    distribution: 'temurin'
                    java-version: ${{ matrix.java }}
                    cache: 'maven'

            -   name: Build Samples with Maven (JDK ${{ matrix.Java }})
                run: mvn clean package
                working-directory: samples
