name: UI Tests

on:
    push:
        branches: [ master, develop*, release* ]
    pull_request:
        branches: [ master, develop*, release* ]
    workflow_dispatch:

env:
    node-version: 14.x

jobs:
    uilint:
        runs-on: ubuntu-latest
        name: Run Linters
        steps:
            -   uses: actions/checkout@v3
            -   name: Use Node v${{ env.node-version }}
                uses: actions/setup-node@v3
                with:
                    node-version: ${{ env.node-version }}
            -   name: Install NPM Dependencies
                run: npm ci
                working-directory: ui.apps
            -   name: Run Linting & Tests
                run: npm run lint
                working-directory: ui.apps
